### ISSUE TITLE
[Omen] - Refactor Css in `GelatoScheduler.tsx` to reflect Figma Mockups

### ISSUE THREAD

**Issue by hilmarx** [gelatodigital/gelato-omen#10]
Most of the styling is already done, however some minor adjustments still have to be made to reflect the exact Figma mockups. Also, some refactoring can be done on the GelatoScheduler component to share styles among various subcomponent. 

You should get rid of any in-line css within the return() statement itself, all styling should be done using the `styled` library 

**Mockups:**

- [Prototype](https://www.figma.com/proto/GNoehJ64fqfptghsjYqvTJ/Playground-V2?node-id=3715%3A783&viewport=293%2C324%2C0.21271684765815735&scaling=min-zoom)
- [Gelato Scheduled](https://www.figma.com/file/MjOlrVUATD0wVzTxAwyii7/Components?node-id=979%3A1683)
- [Gelato Failed](https://www.figma.com/file/MjOlrVUATD0wVzTxAwyii7/Components?node-id=979%3A1683)
- [Gelato successful](https://www.figma.com/file/MjOlrVUATD0wVzTxAwyii7/Components?node-id=979%3A1683)

**Comment by hilmarx** [comment]
this includes #15

**Comment by hilmarx** [comment]
One thing that should be improved for example is the following

**Comment by hilmarx** [comment]
![Uploading Screenshot 2020-11-10 at 12.11.20.png…]()

**Comment by kassandraoftroy** [comment]
done (as best as possible) [here](https://github.com/gelatodigital/omen-exchange/pull/1/commits/37f9cf0528b0480d55ea6086cb0b3795e93014df)
