### ISSUE TITLE
[Omen] - Refactor useGelatoSubmittedTasks to use newly updated Omen Subgraph

### ISSUE THREAD

**Issue by hilmarx** [gelatodigital/gelato-omen#12]
Blocked by #11.

For a reference, check out the `omen-exchange/app/src/hooks/use24hsVolume.ts` hook and refactor the gelato `useGelatoSubmittedTasks` hook to mimic it, based upon the PR of integrating Gelato into Omen’s subgraph having beed merged by the dxDAO team.

**Comment by hilmarx** [comment]
Use this Subgraph for Rinkeby as long as DxDAO has not updated theirs yet:

https://thegraph.com/explorer/subgraph/hilmarx/omen-gelato

**Comment by kassandraoftroy** [comment]
done [here](https://github.com/gelatodigital/omen-exchange/pull/1/commits/71ff29ab042abbb4e9bd44cf8a3ad0f3580ab6f8)
