### ISSUE TITLE
[Omen] - Rebase current branch from origin/master and re-enable Task creation

### ISSUE THREAD

**Issue by hilmarx** [gelatodigital/gelato-omen#35]
**Goal:** 

Be able to schedule automated withdrawal tasks using the old contracts that are deployed. 

**Note:**

As you will already use the new core, you will not be able to query the submitted tasks, hence to test this feature we first need to update the GelatoCore address on the UI

**Comment by kassandraoftroy** [comment]
done [here](https://github.com/gelatodigital/omen-exchange/pull/1/commits/3e4ea742290c2b47497622b5f69d209cb63e66fe)
