### ISSUE TITLE
Change min required amount from deposit amount to total amount after tx gets mined

### ISSUE THREAD

**Issue by hilmarx** [gelatodigital/gelato-omen#44]
If a user wants to access the gelato auto withdraw, we currently require the account to deposit a min. deposit amount that is greater than 100 DAI. 

However, in some cases, maybe the user already provided some funds and simply wants to add a smaller amount later on which does not exceed that balance. The user might still have enough collateral already in the liquidity pool for the transaction to be successfully executed. 

To Do:

- [ ] Change taking the amount that the user will deposit in the transaction as a basis of calculating the min required amount to taking the amount of collateral that he use will have deposited in total, after the transaction will go through (taking into account previous deposits).

**Comment by kassandraoftroy** [comment]
done [here](https://github.com/gelatodigital/omen-exchange/pull/1/commits/7469280fb5c961a4c65f0bbdb6a720290870ae77) pending review
