### ISSUE TITLE
Change the Error message when Users have insufficient collateral balance to submit task

### ISSUE THREAD

**Issue by hilmarx** [gelatodigital/gelato-omen#45]
If Users have an insufficient collateral balance when submitting the task, they should be returned an Error message in the modal that states what is the minimum required collateral amount they have to deposit in the transaction in order to activate the Gelato automation. 

See l.678 in cpk.tsk

**Comment by superarius** [comment]
hey I know you put this in your PR but I decided to just copy your idea and extend it and add it as a commit on my own branch so when you rebase it should be there...

I did however notice one other thing which is an error handling is not implemented on `market_create` in the same way so we can't see it there. If you have an idea for how to fix that... I wasn't sure and didn't want to meddle too much with code that wasn't gelato specific

**Comment by kassandraoftroy** [comment]
done [here](https://github.com/gelatodigital/omen-exchange/pull/1/commits/9482ec14dcbd9c7526098075f3e2fe3483d6d4c8) for `market_pool_liquidity` (when adding liquidity to existing market)

however does not exist on `market_create`

see #47
