### ISSUE TITLE
Make Gelato feature optional

### ISSUE THREAD

**Issue by hilmarx** [gelatodigital/gelato-omen#46]
Before submitting the PR, we should try to refactor the codebase in such a way to have a constant that Omen devs can set which will activate or deactivate the gelato auto withdraw feature.

**Reasoning:**

I believe Omen devs are currently also deploying Omen on different chains, for example xDAI. However, Gelato currently does not operate on xDAI which would make our integration with them incompatible for their xDAI deployment. 

This could lead to a scenario which makes Omen devs reluctant to merge a PR. We could make their lives easier by refactoring the code to them having the ability to just "switch off" all gelato logic if they dont want to use it. 

This would probably mean introducing a lot of `if( GELATO_ACTIVATED)` conditional statements. Let's discuss this.

**Comment by kassandraoftroy** [comment]
[implemented here](https://github.com/gelatodigital/omen-exchange/pull/1/commits/93e1c94b97b15d7e11b398c897b3e7935eff19f5)
