### ISSUE TITLE
[Omen] - Only enable LPs to submit the auto-withdraw task if their provided liquidity exceeds $100 worth of collateral

### ISSUE THREAD

**Issue by hilmarx** [gelatodigital/gelato-omen#7]
To identify whether the selected amount corresponds to $100, use Uniswap Api. Add $100 as a constant in `constants.tx` to use for $ conversions, can use e.g. DAI as $.

**Comment by kassandraoftroy** [comment]
done [here](https://github.com/gelatodigital/omen-exchange/pull/1/commits/eb26285c7c7ccc569ea51185a36aa8c3b919d8cb)
