### ISSUE TITLE
[Omen] - Include Text about Gelato in MarketWizardCreatorContainer Modal when creating new market

### ISSUE THREAD

**Issue by hilmarx** [gelatodigital/gelato-omen#9]
When creating a new market in `MarketWizardCreatorContainer`, display in the modal, before the user confirms the transaction on Metamask, that, if Gelato auto withdraw was selected, that the user will “Create a new market AND schedules an auto withdraw using gelato”. This should be done in the handleSubmit() func. You might need to move the `gelatoData` state up or pass a variable to the submit function which identifies whether gelato was selected or not

**Comment by kassandraoftroy** [comment]
done [here](https://github.com/gelatodigital/omen-exchange/pull/1/commits/71ff29ab042abbb4e9bd44cf8a3ad0f3580ab6f8#diff-98f9394d4e3e8988720467b26c85d67eee586f62ba1e83a1be5dc4ba31877665R518)
